# Generated by Django 4.0.4 on 2022-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_toatal_price_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False, help_text='0-default,1-hidden'),
        ),
    ]
